---

- name: Copy template smb.conf 
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root


- name: Create samba paths
  file:
    path: "/var/spool/samba/{{item}}"
    state: directory
    group: users
  with_items:
    - public
 
